C=======================================================================
C  ALLMECH.EXT
C  This include file contains all number of mechanism species.
C
C
C  Mechanism Name: SAPRCII, SAPRC99, RADM2, RACM, and CBMZ
C  MEGAN v2.02
C  INPUT version 200
C
C  History:
C  Who          When       What
C  ---------------------------------------------------------------------
C  Tan          12/02/06 - Creates this file
C  Tan          08/14/07 - Move from MEGAN v2.0 to MEGAN v2.02 with no update.
C=======================================================================

      INTEGER        N_SAPRCII_SPC
      PARAMETER     (N_SAPRCII_SPC = 31)  ! Number of mechanism species


      INTEGER        N_SAPRC99_SPC
      PARAMETER     (N_SAPRC99_SPC = 28)  ! Number of mechanism species


      INTEGER        N_RADM2_SPC
      PARAMETER     (N_RADM2_SPC = 21)    ! Number of mechanism species


      INTEGER        N_RACM_SPC
      PARAMETER     (N_RACM_SPC = 23)     ! Number of mechanism species


      INTEGER        N_CBMZ_SPC
      PARAMETER     (N_CBMZ_SPC = 23)     ! Number of mechanism species


      INTEGER        N_CBM4_SPC
      PARAMETER     (N_CBM4_SPC = 24)     ! Number of mechanism species
